version: '2'
services:
  niaobulashi-admin:
    image: niaobulashi/admin
    ports:
      - "8080:8080"
    environment:
      - spring.profiles.active=dev
  niaobulashi-api:
    image: niaobulashi/api
    ports:
      - "8081:8081"
    environment:
      - spring.profiles.active=dev